force-app/main/default/objects/Bug_Tracking__c/Bug_Tracking__c.object-meta.xml
<CustomObject>
    <description>When any known or unknown exception occur, The error trace will be recorded here as a &quot;Bug Tracking&quot; object.</description>
    <label>Bug Tracking</label>
    <nameField>
        <displayFormat>Bug-{000000000}</displayFormat>
        <label>Bug Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bug Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bug_Tracking__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>The cause of the error</description>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bug_Tracking__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blocker</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Trivial</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BugTracking_Configuration__c/BugTracking_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Has the queue details to which emails should be routed and configuration of x days after which bug tracking data will be cleaned from the system</description>
    <label>BugTracking_Configuration</label>
</CustomObject>

force-app/main/default/objects/BugTracking_Configuration__c/fields/Days_Before__c.field-meta.xml
<CustomField>
    <fullName>Days_Before__c</fullName>
    <defaultValue>45</defaultValue>
    <description>Has the configuration of x days after which bug tracking data will be cleaned from the system</description>
    <label>Days Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Bugdatacleaning_Batch_Test.cls
@isTest
public class Bugdatacleaning_Batch_Test
{
  public static string query;
    
     public static testmethod void bugdatacleaning_Batch_method()
     {
        list<Bug_Tracking__c> buglist = new list<Bug_Tracking__c>();
        Bug_Tracking__c  BT = new Bug_Tracking__c();
        BT.Class_Name__c = 'Bugdatacleaning_Batch';
        BT.Error__c = 'System.NullPointerException: Attempted to upsert a null list';
        BT.Severity__c = 'Major';
        buglist.add(BT);
        
        Bug_Tracking__c  BT1 = new Bug_Tracking__c();
        BT1.Class_Name__c = 'Bugdatacleaning_sche';
        BT1.Error__c = 'System.NullPointerException: Attempted to upsert a null list';
        BT1.Severity__c = 'Major';
        buglist.add(BT1);
        
        BugTracking_Configuration__c objBugClean = new BugTracking_Configuration__c();
        objBugClean.Name = 'BugDataCleaning_Config';
        objBugClean.Days_Before__c = 30;
        
        
        test.StartTest();
        insert buglist;
        insert objBugClean;
        test.Stoptest();
    
            query = 'SELECT Class_Name__c,CreatedDate FROM Bug_Tracking__c where CreatedDate < today ';
            Bugdatacleaning_Batch bugdata = new Bugdatacleaning_Batch(query);
            
            bugdata .start(null);
            try{
            bugdata .execute(null,buglist);
            }
            catch(DMLexception ex)
            {system.debug('exception ===>'+Ex);}
            bugdata .finish(null);     
         
         }
         
 }
 /*static testMethod void testBatchBugDataCleaning() {
        // TO DO: implement unit test
        String query = 'select name from Bug_Tracking__c';
        test.startTest();
        Bug_Tracking__c bugRecord = new Bug_Tracking__c();
        BugDataCleaning_Config__c objBugClean = new BugDataCleaning_Config__c();
        objBugClean.Name = 'BugDataCleaning_Config';
        objBugClean.Days_Before__c = 30;
            insert objBugClean;
        //bugRecord.Name = 'TestBug';
        system.debug(''+query);
        Batch_BugDataCleaning bugDataObj = new Batch_BugDataCleaning(query);
        database.executeBatch(bugDataObj, 10);
        BugDataCleaning_Scheduler sco = new BugDataCleaning_Scheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('visit Creates', sch, sco);
        /*Database.BatchableContext BC; 
        list<sObject> lstScope = new  list<sObject>();
        Database.Querylocator locator = bugDataObj.start(BC);
        system.Assert(locator != null);
        bugDataObj.execute(BC,lstScope);        
        bugDataObj.finish(BC);*/
        //test.StopTest();*/