force-app/main/default/objects/Bug_Tracking__c/Bug_Tracking__c.object-meta.xml
<CustomObject>
    <description>When any known or unknown exception occur, The error trace will be recorded here as a &quot;Bug Tracking&quot; object.</description>
    <label>Bug Tracking</label>
    <nameField>
        <displayFormat>Bug-{000000000}</displayFormat>
        <label>Bug Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bug Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bug_Tracking__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>The cause of the error</description>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Bug_Tracking__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blocker</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Trivial</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BugTracking_Configuration__c/BugTracking_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Has the queue details to which emails should be routed and configuration of x days after which bug tracking data will be cleaned from the system</description>
    <label>BugTracking_Configuration</label>
</CustomObject>

force-app/main/default/objects/BugTracking_Configuration__c/fields/Days_Before__c.field-meta.xml
<CustomField>
    <fullName>Days_Before__c</fullName>
    <defaultValue>45</defaultValue>
    <description>Has the configuration of x days after which bug tracking data will be cleaned from the system</description>
    <label>Days Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BugDataCleaning_Sche_Test.cls
@isTest		//(seealldata = true)
public class BugDataCleaning_Sche_Test{
    public static string query1;
   
    public static testmethod void BugDataCleaning_Sche_Method()
    {
     List<Bug_Tracking__c> BugList = new List<Bug_Tracking__c>();
     Bug_Tracking__c  BugTrack = new Bug_Tracking__c();
     BugTrack .Class_Name__c = 'Bugdatacleaning_Batch';
     BugTrack .Error__c = 'System.NullPointerException: Attempted to upsert a null list';
     BugTrack .Severity__c = 'Major';
     BugList.add(BugTrack ); 
      
     query1 = 'SELECT Class_Name__c,CreatedDate FROM Bug_Tracking__c where CreatedDate < today'; 
     BugDataCleaning_Sche BatchCleanSche = new BugDataCleaning_Sche();
     
             
     try{
     test.StartTest();
     insert BugList;
     test.Stoptest();
      
     BatchCleanSche.execute(null);
     Bugdatacleaning_Batch BugBatch = new Bugdatacleaning_Batch (query1); 
     //BatchCleanSche.getbugdatacleaning();        
                          
      }
      catch(Exception bsExc){ 
      system.debug('@@@->'+bsExc);
      }
           
     }
     
     public static testmethod void testgetbugdatacleaning()
     {
      BugTracking_Configuration__c objBugClean = new BugTracking_Configuration__c();
     try{
     
        objBugClean.Name = 'BugDataCleaning_Config';
        objBugClean.Days_Before__c = 45;
            insert objBugClean;
         Test.startTest();
         new BugDataCleaning_Sche().query1(objBugClean);
         Test.stopTest();
      }
     catch(DMLException dmlEx){ 
     system.debug('@@@->'+dmlex);
     }
    }
}