force-app/main/default/objects/Bug_Tracking__c/Bug_Tracking__c.object-meta.xml
<CustomObject>
    <description>When any known or unknown exception occur, The error trace will be recorded here as a &quot;Bug Tracking&quot; object.</description>
    <label>Bug Tracking</label>
    <nameField>
        <displayFormat>Bug-{000000000}</displayFormat>
        <label>Bug Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bug Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BugTracking_Configuration__c/BugTracking_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Has the queue details to which emails should be routed and configuration of x days after which bug tracking data will be cleaned from the system</description>
    <label>BugTracking_Configuration</label>
</CustomObject>

force-app/main/default/objects/BugTracking_Configuration__c/fields/Days_Before__c.field-meta.xml
<CustomField>
    <fullName>Days_Before__c</fullName>
    <defaultValue>45</defaultValue>
    <description>Has the configuration of x days after which bug tracking data will be cleaned from the system</description>
    <label>Days Before</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BugDataCleaning_Sche.cls
public with sharing class BugDataCleaning_Sche implements Schedulable
{
     public void execute(SchedulableContext SC) 
     { 
        try{
        // Here custom setting information
        BugTracking_Configuration__c bugTraCon = getbugDataCleaning();
        
        // calling Batch class to delete Bug Tracking data
        Bugdatacleaning_Batch bugBatch = new Bugdatacleaning_Batch (query1(bugTraCon));
        database.executeBatch(bugBatch);
         }
        catch(Exception bsExc){ 
        throw new BaseServiceException('Exception occured: BugDataCleaning_Sche : execute method ',bsExc);
                }
         }
    
        public BugTracking_Configuration__c getbugdatacleaning(){
       
                if(BugTracking_Configuration__c.getInstance('BugTrackingConfig') == null){
                      BugTracking_Configuration__c BugTracking = new BugTracking_Configuration__c ();
                      try{
                            BugTracking.Days_Before__c = 45 ;
                            insert BugTracking;
                         }
                      catch(DMLException dmlEx){ 
                      throw new BaseServiceException('Exception occured: BugDataCleaning_Sche : getBugDataCleaning method ',dmlEx);
                }
                
                      return bugTracking;
                }else 
                      return bugTracking_Configuration__c.getInstance('BugTrackingConfig');
          }
          //here retriving data from Bug_Tracking__c with condition
         public String query1(BugTracking_Configuration__c bugTraCon ){
                Integer DaysBefore = Integer.ValueOf(BugTraCon .Days_Before__c);
                return 'SELECT Class_Name__c,CreatedDate FROM Bug_Tracking__c where createddate < LAST_N_DAYS:'+DaysBefore;
          }
}