force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>z-{000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/QuestionId__c.field-meta.xml
<CustomField>
    <fullName>QuestionId__c</fullName>
    <displayFormat>Q-{000}</displayFormat>
    <label>QuestionId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/ResponseObject__c/ResponseObject__c.object-meta.xml
<CustomObject>
    <label>ResponseObject</label>
    <nameField>
        <label>ResponseObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ResponseObject__c/fields/CorrectResponse__c.field-meta.xml
<CustomField>
    <fullName>CorrectResponse__c</fullName>
    <label>CorrectResponse</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResponseObject__c/fields/QuestionId__c.field-meta.xml
<CustomField>
    <fullName>QuestionId__c</fullName>
    <label>QuestionId</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResponseObject__c/fields/SelectedResponse__c.field-meta.xml
<CustomField>
    <fullName>SelectedResponse__c</fullName>
    <label>SelectedResponse</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ResultController.cls
public class ResultController {
   public integer no_of_questions{get;set;}
        public integer no_of_attempted_questions  {get;set;}
   public  integer no_of_correct_answers{get;set;}
   public Decimal result{get;set;}
    public void OnLoad(){
         no_of_questions =[Select count() From Question__c];
         no_of_attempted_questions=[Select count() From ResponseObject__c];
         no_of_correct_answers=0;
        for(ResponseObject__c r: [SELECT QuestionId__c,SelectedResponse__c,CorrectResponse__c from ResponseObject__c])
        {
            if(r.SelectedResponse__c==r.CorrectResponse__c)
            {
                no_of_correct_answers++;
            }
        }
         result = no_of_correct_answers / no_of_questions  ;
        List<ResponseObject__c> resp = [SELECT QuestionId__c,SelectedResponse__c,CorrectResponse__c from ResponseObject__c];
        delete resp;
    }
}