force-app/main/default/objects/PageLog__c/PageLog__c.object-meta.xml
<CustomObject>
    <label>PageLog</label>
    <nameField>
        <label>PageLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PageLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PageLog__c/fields/Page_Accessed_time__c.field-meta.xml
<CustomField>
    <fullName>Page_Accessed_time__c</fullName>
    <label>Page Accessed time</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PageLog__c/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <label>PageName</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FirstPageController.cls
public class FirstPageController {
    
public void OnLoad()
   {
       String user_name = UserInfo.getName();
      String strurl = ApexPages.currentPage().getUrl();
 strurl = strurl.split('apex/')[1];
       try{
          PageLog__c p = new PageLog__c();
           p.PageName__c= strurl;
           p.Page_Accessed_time__c= date.today().format();
           p.Username__c = user_name;
           insert p;
           System.debug('value inserted');
       }
       catch(Exception e)
       {
           System.debug('DML Exception' + e.getCause());
       }
      System.debug(' username is' + user_name+ 'page name is '+ strurl  );
       
       
   }
}