force-app/main/default/objects/EmailDomainList__c/EmailDomainList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A custom setting to update all the email domains being added as part of the project</description>
    <label>EmailDomainList</label>
</CustomObject>

force-app/main/default/objects/EmailDomainList__c/fields/DomainName__c.field-meta.xml
<CustomField>
    <fullName>DomainName__c</fullName>
    <label>DomainName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UtilityHelper_Test.cls
@isTest
public class UtilityHelper_Test {
	public static Testmethod void MyTest(){
        List<String> newEmailIdList = new List<String>();
        newEmailIdList.add('rp@g.com');
        newEmailIdList.add('ms@gmail.com');
        newEmailIdList.add('d@m.com');
        EmailDomainList__c emailDomainObj = new EmailDomainList__c();
		emailDomainObj.name = 'p.com';
		emailDomainObj.DomainName__c = 'p.com';
        insert emailDomainObj;
    	Test.startTest();
        UtilityHelper.processNewEmailDomainList(newEmailIdList);
        try{
            newEmailIdList.add('m.com');
            UtilityHelper.processNewEmailDomainList(newEmailIdList);
        }catch(BaseServiceException e){}
        Test.stopTest();
    }
}